apm install atom-beautify
apm install block-comment
apm install editorconfig
apm install emmet
apm install git-control
apm install git-plus
apm install git-time-machine
apm install language-babel
apm install language-ejs
apm install language-javascript-jsx
apm install linter
apm install linter-ui-default
apm install linter-eslint
apm install linter-js-standard
apm install local-history
apm install markdown-preview-plus
apm install minimap
apm install pigments
apm install platformio-ide-terminal
apm install pretty-json
apm install script
apm install seti-ui
apm install sort-lines
apm install todo-show
apm install Sublime-Style-Column-Selection
apm install nuclide
